[settings]
windows_shim_mode = "symlink"
python.uv_venv_auto = true

[tools]
uv = "0.9.28"

[env]
'_'.python.venv = { path = ".venv" }
PYTHONUNBUFFERED = 1
PYTHONDONTWRITEBYTECODE = 1
UV_LINK_MODE = "copy"
